<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Tabela.aspx.cs" Inherits="AppWeb.Tabela" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="gvCarros" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="gvCarros_RowDeleting"></asp:GridView>
</asp:Content>
